//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassEnrollment
    {
        public int Id { get; set; }
        public int ClassroomId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Student Student { get; set; }
    }
}
